In [ ]:
pip install fredapi

In [ ]:
from fredapi import Fred
import pandas as pd

# Replace 'your_api_key' with your actual FRED API key
fred = Fred(api_key='23f25ddc12b4ef4c917e4ae0ae317410')

# List of series IDs to fetch
series_ids = [
    'USREC', 'INDPRO', 'PAYEMS', 'RPI', 'UNRATE',  'GS10'
]

start_date = '1983-01-01'
end_date = '2023-12-01'

# Fetch the data for each series and store in a dictionary
data = {series_id: fred.get_series(series_id, start_date, end_date) for series_id in series_ids}

# Convert dictionary to DataFrame
df = pd.DataFrame(data)

for column in ['INDPRO', 'PAYEMS', 'RPI', 'UNRATE']:  # Specify columns to lag
    df[f'{column}_lagged_{1}'] = df[column].shift(1)

for column in ['GS10']:  # Specify columns to lag
    df[f'{column}_lagged_{6}'] = df[column].shift(6)
    df[f'{column}_lagged_{12}'] = df[column].shift(12)

df

USREC    INDPRO    PAYEMS        RPI  UNRATE   GS10  \
1983-01-01    0.0   47.7398   88990.0   6279.297    10.4  10.46   
1983-02-01    0.0   47.4484   88917.0   6283.890    10.4  10.72   
1983-03-01    0.0   47.8426   89090.0   6314.258    10.3  10.51   
1983-04-01    0.0   48.4483   89364.0   6319.274    10.2  10.40   
1983-05-01    0.0   48.7470   89644.0   6351.636    10.1  10.38   
...           ...       ...       ...        ...     ...    ...   
2023-08-01    0.0  103.0951  156421.0  19117.491     3.8   4.17   
2023-09-01    0.0  103.3081  156667.0  19111.748     3.8   4.38   
2023-10-01    0.0  102.5781  156832.0  19115.984     3.8   4.80   
2023-11-01    0.0  102.8868  157014.0  19161.004     3.7   4.50   
2023-12-01    0.0  102.6309  157304.0  19194.730     3.7   4.02   

            INDPRO_lagged_1  PAYEMS_lagged_1  RPI_lagged_1  UNRATE_lagged_1  \
1983-01-01              NaN              NaN           NaN              NaN   
1983-02-01          47.7398          88990.0      6279.297             10.4   
1983-03-01          47.4484          88917.0      6283.890             10.4   
1983-04-01          47.8426          89090.0      6314.258             10.3   
1983-05-01          48.4483          89364.0      6319.274             10.2   
...                     ...              ...           ...              ...   
2023-08-01         103.0722         156211.0     19095.937              3.5   
2023-09-01         103.0951         156421.0     19117.491              3.8   
2023-10-01         103.3081         156667.0     19111.748              3.8   
2023-11-01         102.5781         156832.0     19115.984              3.8   
2023-12-01         102.8868         157014.0     19161.004              3.7   

            GS10_lagged_6  GS10_lagged_12  
1983-01-01            NaN             NaN  
1983-02-01            NaN             NaN  
1983-03-01            NaN             NaN  
1983-04-01            NaN             NaN  
1983-05-01            NaN             NaN  
...                   ...             ...  
2023-08-01           3.75            2.90  
2023-09-01           3.66            3.52  
2023-10-01           3.46            3.98  
2023-11-01           3.57            3.89  
2023-12-01           3.75            3.62  

[492 rows x 12 columns]

In [ ]:
df_1 = df.dropna()
df_1

USREC    INDPRO    PAYEMS        RPI  UNRATE   GS10  \
1984-01-01    0.0   53.0088   92673.0   6603.030     8.0  11.67   
1984-02-01    0.0   53.2486   93157.0   6639.713     7.8  11.84   
1984-03-01    0.0   53.5028   93429.0   6679.057     7.8  12.32   
1984-04-01    0.0   53.8233   93792.0   6721.247     7.7  12.63   
1984-05-01    0.0   54.1104   94098.0   6735.713     7.4  13.41   
...           ...       ...       ...        ...     ...    ...   
2023-08-01    0.0  103.0951  156421.0  19117.491     3.8   4.17   
2023-09-01    0.0  103.3081  156667.0  19111.748     3.8   4.38   
2023-10-01    0.0  102.5781  156832.0  19115.984     3.8   4.80   
2023-11-01    0.0  102.8868  157014.0  19161.004     3.7   4.50   
2023-12-01    0.0  102.6309  157304.0  19194.730     3.7   4.02   

            INDPRO_lagged_1  PAYEMS_lagged_1  RPI_lagged_1  UNRATE_lagged_1  \
1984-01-01          51.9769          92230.0      6581.287              8.3   
1984-02-01          53.0088          92673.0      6603.030              8.0   
1984-03-01          53.2486          93157.0      6639.713              7.8   
1984-04-01          53.5028          93429.0      6679.057              7.8   
1984-05-01          53.8233          93792.0      6721.247              7.7   
...                     ...              ...           ...              ...   
2023-08-01         103.0722         156211.0     19095.937              3.5   
2023-09-01         103.0951         156421.0     19117.491              3.8   
2023-10-01         103.3081         156667.0     19111.748              3.8   
2023-11-01         102.5781         156832.0     19115.984              3.8   
2023-12-01         102.8868         157014.0     19161.004              3.7   

            GS10_lagged_6  GS10_lagged_12  
1984-01-01          11.38           10.46  
1984-02-01          11.85           10.72  
1984-03-01          11.65           10.51  
1984-04-01          11.54           10.40  
1984-05-01          11.69           10.38  
...                   ...             ...  
2023-08-01           3.75            2.90  
2023-09-01           3.66            3.52  
2023-10-01           3.46            3.98  
2023-11-01           3.57            3.89  
2023-12-01           3.75            3.62  

[480 rows x 12 columns]

In [ ]:
summary_stats = df_1.describe()
summary_stats

USREC      INDPRO         PAYEMS           RPI      UNRATE  \
count  480.000000  480.000000     480.000000    480.000000  480.000000   
mean     0.075000   84.925469  127743.420833  12461.097883    5.864375   
std      0.263666   16.734865   16285.103468   3753.244045    1.666382   
min      0.000000   53.008800   92673.000000   6603.030000    3.400000   
25%      0.000000   66.707600  112529.500000   8835.039750    4.600000   
50%      0.000000   91.267800  131006.000000  12350.800500    5.600000   
75%      0.000000   99.060975  138121.000000  14957.543500    6.900000   
max      1.000000  104.103800  157304.000000  22856.702000   14.800000   

             GS10  INDPRO_lagged_1  PAYEMS_lagged_1  RPI_lagged_1  \
count  480.000000       480.000000       480.000000    480.000000   
mean     5.024958        84.819940    127607.850000  12434.819877   
std      2.690658        16.782625     16309.349885   3750.155373   
min      0.620000        51.976900     92230.000000   6581.287000   
25%      2.757500        66.457225    112240.500000   8815.279250   
50%      4.585000        91.193700    130993.500000  12341.109500   
75%      6.832500        99.047550    138079.750000  14893.556500   
max     13.560000       104.103800    157014.000000  22856.702000   

       UNRATE_lagged_1  GS10_lagged_6  GS10_lagged_12  
count       480.000000     480.000000      480.000000  
mean          5.873958       5.116979        5.203646  
std           1.667136       2.788288        2.847697  
min           3.400000       0.620000        0.620000  
25%           4.675000       2.757500        2.757500  
50%           5.600000       4.680000        4.725000  
75%           6.900000       6.985000        7.125000  
max          14.800000      13.560000       13.560000

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df_standardized = scaler.fit_transform(df_1)

df_standardized = pd.DataFrame(df_standardized, columns=df_1.columns)

In [ ]:
df_standardized

USREC    INDPRO    PAYEMS       RPI    UNRATE      GS10  \
0   -0.284747 -1.909186 -2.155774 -1.562430  1.282931  2.472248   
1   -0.284747 -1.894842 -2.126023 -1.552646  1.162785  2.535496   
2   -0.284747 -1.879636 -2.109303 -1.542152  1.162785  2.714077   
3   -0.284747 -1.860464 -2.086990 -1.530899  1.102713  2.829411   
4   -0.284747 -1.843291 -2.068180 -1.527041  0.922494  3.119605   
..        ...       ...       ...       ...       ...       ...   
475 -0.284747  1.086868  1.762807  1.775354 -1.240129 -0.318082   
476 -0.284747  1.099609  1.777929  1.773822 -1.240129 -0.239953   
477 -0.284747  1.055942  1.788071  1.774952 -1.240129 -0.083694   
478 -0.284747  1.074408  1.799259  1.786960 -1.300202 -0.195308   
479 -0.284747  1.059100  1.817085  1.795955 -1.300202 -0.373889   

     INDPRO_lagged_1  PAYEMS_lagged_1  RPI_lagged_1  UNRATE_lagged_1  \
0          -1.959008        -2.171439     -1.562506         1.456734   
1          -1.897458        -2.144248     -1.556702         1.276597   
2          -1.883155        -2.114541     -1.546910         1.156505   
3          -1.867992        -2.097846     -1.536408         1.156505   
4          -1.848875        -2.075566     -1.525146         1.096460   
..               ...              ...           ...              ...   
475         1.088704         1.755618      1.778077        -1.425460   
476         1.090069         1.768508      1.783831        -1.245323   
477         1.102774         1.783607      1.782298        -1.245323   
478         1.059232         1.793734      1.783429        -1.245323   
479         1.077645         1.804905      1.795446        -1.305369   

     GS10_lagged_6  GS10_lagged_12  
0         2.248532        1.847752  
1         2.417270        1.939149  
2         2.345466        1.865329  
3         2.305975        1.826661  
4         2.359827        1.819630  
..             ...             ...  
475      -0.490769       -0.809795  
476      -0.523080       -0.591848  
477      -0.594884       -0.430145  
478      -0.555392       -0.461782  
479      -0.490769       -0.556695  

[480 rows x 12 columns]

In [ ]:
from sklearn.model_selection import train_test_split

y = df_1['USREC']
x = df_1.drop(['USREC'], axis = 1)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

#Probit Regression

In [ ]:
import statsmodels.api as sm
from sklearn.metrics import classification_report, confusion_matrix

x = sm.add_constant(x)

# Fit probit model
probit_model = sm.Probit(y_train, x_train)
probit_result = probit_model.fit()
print(probit_result.summary())

         Current function value: 0.000000
         Iterations: 35
                          Probit Regression Results                           
Dep. Variable:                  USREC   No. Observations:                  336
Model:                         Probit   Df Residuals:                      325
Method:                           MLE   Df Model:                           10
Date:                Sat, 13 Jul 2024   Pseudo R-squ.:                   1.000
Time:                        21:15:30   Log-Likelihood:            -3.2695e-05
converged:                      False   LL-Null:                       -91.501
Covariance Type:            nonrobust   LLR p-value:                 5.574e-34
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
INDPRO           -176.8672   4.41e+05     -0.000      1.000   -8.65e+05    8.65e+05
PAYEMS             -0.7748   1084.167     -0.001  

/usr/local/lib/python3.10/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


In [ ]:
import numpy as np

# Predicted probabilities
y_prob = probit_result.predict(x_test)

# Convert probabilities to binary predictions (using 0.5 threshold)
y_pred = np.where(y_prob >= 0.5, 1, 0)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[130   4]
 [  2   8]]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.98      0.97      0.98       134
         1.0       0.67      0.80      0.73        10

    accuracy                           0.96       144
   macro avg       0.83      0.89      0.85       144
weighted avg       0.96      0.96      0.96       144



#KNN Model

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train, y_train)

y_pred = knn.predict(x_test)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[134   0]
 [  7   3]]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.95      1.00      0.97       134
         1.0       1.00      0.30      0.46        10

    accuracy                           0.95       144
   macro avg       0.98      0.65      0.72       144
weighted avg       0.95      0.95      0.94       144



#Decision Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

forest = RandomForestClassifier(n_estimators=100)
forest.fit(x_train, y_train)

y_pred = forest.predict(x_test)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[134   0]
 [  4   6]]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.97      1.00      0.99       134
         1.0       1.00      0.60      0.75        10

    accuracy                           0.97       144
   macro avg       0.99      0.80      0.87       144
weighted avg       0.97      0.97      0.97       144



#Ridge Classification

In [ ]:
from sklearn.linear_model import RidgeClassifier

ridge_clf = RidgeClassifier(alpha=1.0)
ridge_clf.fit(x_train, y_train)

y_pred = ridge_clf.predict(x_test)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[134   0]
 [  8   2]]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.94      1.00      0.97       134
         1.0       1.00      0.20      0.33        10

    accuracy                           0.94       144
   macro avg       0.97      0.60      0.65       144
weighted avg       0.95      0.94      0.93       144



#Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

# Train the model
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[132   2]
 [  4   6]]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.97      0.99      0.98       134
         1.0       0.75      0.60      0.67        10

    accuracy                           0.96       144
   macro avg       0.86      0.79      0.82       144
weighted avg       0.96      0.96      0.96       144



#GBM

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

gbm = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state = 42)

# Train the model
gbm.fit(x_train, y_train)

y_pred = gbm.predict(x_test)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[134   0]
 [  3   7]]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99       134
         1.0       1.00      0.70      0.82        10

    accuracy                           0.98       144
   macro avg       0.99      0.85      0.91       144
weighted avg       0.98      0.98      0.98       144

